### ISSUE TITLE
Pick and apply a cell style? HowTo?

### ISSUE THREAD

**Issue by zohozer** [karakasa/PancakeSpreadsheet#2]
Do you also have an example how I can apply a cell style from existing spreadsheet to a new created set of cells? I want to apply the style Labeled CNC or BSAW or MT from the cell A5 to the cells nr.5 of the created cuttinglist.

![Style_choose](https://user-images.githubusercontent.com/5983791/194762678-4a76682d-69f5-4832-a347-8861a3811862.png)

[Style_choose.xlsx](https://github.com/karakasa/PancakeSpreadsheet/files/9741795/Style_choose.xlsx)

Best regards.

**Comment by karakasa** [comment]
@zohozer 

I don't quite understand your request. By "cell style", it means background color, cell format, etc. 

You may try to use the Clone Cell Style component. If that fails, I'd say duplicating labels might not be supported yet.

**Comment by zohozer** [comment]
As in my first picture, I don't understand how I can create a "Cell reference".

Yes, the color and text formatting. I provided an example file [Style_choose.xlsx](https://github.com/karakasa/PancakeSpreadsheet/files/9741795/Style_choose.xlsx) where every cell have an option to choose from three diferent styles. One it is labelled "CNC" (red color) , the other it is labelled "BSAW" (green color) and the third one it is labbeled "MT" (blue color). How can I choose one of this styles that I do have into that spreadsheet?

In LibreOffice it is shown like this:
![Style_choose](https://user-images.githubusercontent.com/5983791/196031863-6d911b3a-cabe-4168-8404-b3a784a9496d.png)

**Comment by karakasa** [comment]
These formats are done by conditional formatting, which is not fully supported by the underlying NPOI library (nor is NPOI's grandparent apache/poi), which PancakeSpreadshset uses to manipulate XLSX files.

I tried on your spreadsheet and found NPOI cannot handle the formatting. Hence I'm afraid PancakeSpreadsheet wouldn't support such feature any time soon.
