### ISSUE TITLE
'Format as table' can cause errors when reading a sheet 

### ISSUE THREAD

**Issue by Intuos5** [karakasa/PancakeSpreadsheet#3]
It appears that the plugin fails to read the sheet range or sheets themselves correctly when I format cells as table. 
![afbeelding](https://user-images.githubusercontent.com/63149655/225419771-be2f8f1b-abfe-4bd5-9220-95bd740d3577.png)

This is a sample table that caused the issues when I formatted it:
![afbeelding](https://user-images.githubusercontent.com/63149655/225420273-283165ce-b23f-4337-b166-26dd15174fdc.png)

When I remove this formatting and leave the cells as plain text or simple sum() formula, the sheets and data read fine.

**Comment by karakasa** [comment]
May you upload the formatted spreadsheet you have issues with?

**Comment by Intuos5** [comment]
Yes of course, here you go:
[Street profiles_tables-formatted.xlsx](https://github.com/karakasa/PancakeSpreadsheet/files/10988467/Street.profiles_tables-formatted.xlsx)

**Comment by karakasa** [comment]
It works here. Do I miss anything?

![image](https://user-images.githubusercontent.com/12855165/225806825-cbd5420f-52f6-4e8b-ba23-b70db687ba84.png)

**Comment by Intuos5** [comment]
Forgot to mention that I am using the WIP with the .Net runtime set to Default (`setdotnetruntime` command).
I tested it with Rhino 7 as well and the result is the same. The issue is with Simple Read XLS specifically, it seems.

See script below:
[Read XLS (simple) for formatted sheets.zip](https://github.com/karakasa/PancakeSpreadsheet/files/10998545/Read.XLS.simple.for.formatted.sheets.zip)

**Comment by karakasa** [comment]
> Forgot to mention that I am using the WIP with the .Net runtime set to Default (`setdotnetruntime` command). I tested it with Rhino 7 as well and the result is the same. The issue is with Simple Read XLS specifically, it seems.
> 
> See script below: [Read XLS (simple) for formatted sheets.zip](https://github.com/karakasa/PancakeSpreadsheet/files/10998545/Read.XLS.simple.for.formatted.sheets.zip)

Apologize I didn't have time for quite a long time. As for your 1st question, you need to wire a True value to the OK input. I added a notification.

![image](https://user-images.githubusercontent.com/12855165/231994746-53624353-aefd-48e1-bd06-186327498291.png)

![image](https://user-images.githubusercontent.com/12855165/231997452-f0115009-d8f2-474c-8660-fec9bc7039c6.png)


For your 2nd question I have found the bug and I would implement a fix. You can wire as such for a workaround.

![image](https://user-images.githubusercontent.com/12855165/231996940-9f04890b-ff88-4a94-8074-410131b34279.png)

**Comment by Intuos5** [comment]
Indeed, it has been working fine for me since I last asked.
