### ISSUE TITLE
[Feature request] Auto-refresh data when the referenced Excel file is saved

### ISSUE THREAD

**Issue by Intuos5** [karakasa/PancakeSpreadsheet#4]
Would it be possible to detect changes to the Excel sheet with the "Open Spreadsheet" component when OK is said to true? Ideally, when set to proceed reading the sheet, I would like it to dynamically pull the new data from Excel when I made changes to the file. That saves me from going back to the component to hit the Boolean Toggle for the OK input on every file save. Perhaps this could be an option in the right click menu like with Elefront, where you can set auto-update for the component to true or false in this list:
![afbeelding](https://user-images.githubusercontent.com/63149655/230036199-82a7eaea-c286-4df2-9dcd-3f90cffa6eef.png)

**Comment by karakasa** [comment]
You may use the _Synchorization_ feature of the _File Path_ parameter.

**Warning:** This feature is provided by Grasshopper. It has bugs when the file is on a network location or in a Google Drive/Dropbox folder, etc.

![image](https://user-images.githubusercontent.com/12855165/232010276-1ac5dd62-b7c9-4ab3-9c03-0f49419447ab.png)


https://user-images.githubusercontent.com/12855165/232011501-c3b487d0-8879-4ca8-9a05-21ffd788d2bd.mp4
